global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#hardwork'
