version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${SRVVERS} # 1.0
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - "9292:9292"
    depends_on:
      - post
    networks:
      reddit:
        aliases:
          - comment
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USER_NAME}/post:${SRVVERS} # 1.0
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      reddit:
        aliases:
          - post

  comment:
    image: ${USER_NAME}/comment:${SRVVERS} # 1.0
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      reddit:
#        aliases:
#          - comment

volumes:
  post_db:

networks:
  reddit:


