version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${SRVVERS}
    ports:
      - ${SRVPORT}:${SRVPORT}/tcp
    networks:
      front_net:
        aliases:
          - ui
  post:
    image: ${USERNAME}/post:${SRVVERS}
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment
  comment:
    image: ${USERNAME}/comment:${SRVVERS}
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      front_net:
        aliases:
          - prometheus
  node-exporter:
    image: prom/node-exporter:latest
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      front_net:
        aliases:
          - node-exporter
  mongodb-exporter:
    image: ${USERNAME}/mongodb_exporter:latest
    user: root
    ports:
      - '9216:9216'
    command:
      - '--mongodb.uri=mongodb:27017'
    networks:
      front_net:
        aliases:
          - monfodb-exporter
volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:

