version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${SRVVERS}
    ports:
      - ${SRVPORT}:${SRVPORT}/tcp
    networks:
      front_net:
        aliases:
          - ui
  post:
    image: ${USERNAME}/post:${SRVVERS}
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment
  comment:
    image: ${USERNAME}/comment:${SRVVERS}
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment
  mongodb-exporter:
    image: ${USERNAME}/mongodb_exporter:latest
    user: root
    ports:
      - '9216:9216'
    command:
      - '--mongodb.uri=mongodb:27017'
    networks:
      front_net:
        aliases:
          - monfodb-exporter
volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:

